version: '3'

services:
  client:
    build:
      context: ./packages/client
      dockerfile: ./Dockerfile-development
    command: ['node_modules/.bin/coko-client-dev']
    ports:
      - ${CLIENT_PORT:-4000}:${CLIENT_PORT:-4000}
    environment:
      - NODE_ENV=development
      - CLIENT_PORT=${CLIENT_PORT:-4000}
      - CLIENT_FAST_REFRESH=1
      - CLIENT_FAVICON_PATH=../static/favicon.ico
      - CLIENT_PAGE_TITLE=${CLIENT_PAGE_TITLE:-"Basic App Template"}
      - CLIENT_LANGUAGE=${CLIENT_LANGUAGE:-"en-US"}
      - SERVER_URL=${SERVER_URL:-http://localhost:3000}
    volumes:
      - ./packages/client/app:/home/node/app/app
      - ./packages/client/static:/home/node/app/static
    tty: true

  server:
    build:
      context: ./packages/server
      dockerfile: ./Dockerfile-development
    entrypoint:
      [
        'node_modules/.bin/wait-for-it',
        'dev-ingest-data-22-07-2024.cpcwgoa3uzw1.eu-west-1.rds.amazonaws.com:5432',
        '--',
        'sh',
        'scripts/setupDevServer.sh',
      ]
    command:
      [
        'node_modules/.bin/nodemon',
        'startServer.js',
        '--watch',
        'api',
        '--watch',
        'config',
        '--watch',
        'controllers',
        '--watch',
        'models',
        '--watch',
        'rest',
        '--watch',
        'services',
        '--watch',
        'scripts',
        '--watch',
        '--ext',
        'js,graphql',
      ]
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-dev_db}
      - POSTGRES_USER=${POSTGRES_USER:-dev_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-dev_user_password}
      - PUBSWEET_SECRET=${PUBSWEET_SECRET:-superSecretThing}
      - SERVER_PORT=${SERVER_PORT:-3000}
      - HOSTNAME=${HOSTNAME}
      - CLIENT_URL=${CLIENT_URL:-http://0.0.0.0:4000}
      - MAILER_SENDER=${MAILER_SENDER:-dev@example.com}
      - MAILER_HOSTNAME=${MAILER_HOSTNAME}
      - MAILER_PORT=${MAILER_PORT}
      - MAILER_USER=${MAILER_USER}
      - MAILER_PASSWORD=${MAILER_PASSWORD}
      - PASSWORD_RESET_PATH=${PASSWORD_RESET_PATH:-password-reset}
      - S3_PROTOCOL=http
      - START_YEAR=${START_YEAR}
      - END_YEAR=${END_YEAR}
      - S3_HOST=filehosting
      - S3_PORT=${S3_PORT:-9000}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID:-nonRootUser}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY:-nonRootPassword}
      - S3_BUCKET=${S3_BUCKET:-uploads}
      - S3_CZI_FOLDER_PATH=${S3_CZI_FOLDER_PATH}
    volumes:
      - ./packages/server/api:/home/node/app/api
      - ./packages/server/config:/home/node/app/config
      - ./packages/server/controllers:/home/node/app/controllers
      - ./packages/server/models:/home/node/app/models
      - ./packages/server/rest:/home/node/app/rest
      - ./packages/server/scripts:/home/node/app/scripts
      - ./packages/server/services:/home/node/app/services
