version: '3'

services:
  client:
    build:
      context: ./packages/client
      dockerfile: ./Dockerfile-production
      args:
        - server_url=${SERVER_URL:-http://localhost:3000}
    command: ['npx', 'serve', '-p', '4000', '--single', './_build']
    ports:
      - ${CLIENT_PORT:-4000}:4000
    restart: always

  server:
    build:
      context: ./packages/server
      dockerfile: ./Dockerfile-production
    entrypoint: ['sh', 'scripts/setupDevServer.sh']
    command: ['node', 'startServer.js']
    ports:
      - 3000:3000
    restart: always
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-dev_db}
      - POSTGRES_USER=${POSTGRES_USER:-dev_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-dev_user_password}
      - PUBSWEET_SECRET=${PUBSWEET_SECRET:-superSecretThing}
      - SERVER_PORT=${SERVER_PORT:-3000}
      - HOSTNAME=${HOSTNAME}
      - CLIENT_URL=${CLIENT_URL:-http://0.0.0.0:4000}
      - MAILER_SENDER=${MAILER_SENDER:-dev@example.com}
      - MAILER_HOSTNAME=${MAILER_HOSTNAME}
      - MAILER_PORT=${MAILER_PORT}
      - MAILER_USER=${MAILER_USER}
      - MAILER_PASSWORD=${MAILER_PASSWORD}
      - PASSWORD_RESET_PATH=${PASSWORD_RESET_PATH:-password-reset}
      - S3_PROTOCOL=http
      - START_YEAR=${START_YEAR}
      - END_YEAR=${END_YEAR}
      - S3_HOST=filehosting
      - S3_PORT=${S3_PORT:-9000}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID:-nonRootUser}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY:-nonRootPassword}
      - S3_BUCKET=${S3_BUCKET:-uploads}
      - S3_CZI_FOLDER_PATH=${S3_CZI_FOLDER_PATH}
    volumes:
      - ./packages/server/api:/home/node/app/api
      - ./packages/server/config:/home/node/app/config
      - ./packages/server/controllers:/home/node/app/controllers
      - ./packages/server/models:/home/node/app/models
      - ./packages/server/rest:/home/node/app/rest
      - ./packages/server/scripts:/home/node/app/scripts
      - ./packages/server/services:/home/node/app/services
