const LABEL_REPOSITORY_MAPPING = {
    arrayexpress: 'ArrayExpress',
    biomodels: 'BioModels',
    bioproject: 'BioProject',
    biostudies: 'BioStudies',
    cath:'CATH',
    chebi:'ChEBI (Chemical Entities of Biological Interest)',
    chembl:'ChEMBL',
    complexportal: 'Complex Portal (CP)',
    dbgap:'NCBI dbGaP (DataBase of Genotypes And Phenotypesgenotypes and phenotypes)',
    ebisc: 'EBiSC Catalogue (European Bank for induced pluripotent Stem Cells catalogue)',
    efo: 'Experimental Factor Ontology',
    ega: 'The European Genome-phenome Archive(EGA)',
    emdb: 'The Electron Microscopy Data Bank (EMDB)',
    empiar: 'Electron Microscopy Public Image Archive (EMPIAR)',
    ensembl: 'Ensembl',
    eudract: 'EU Clinical Trial Register(EUCTR)',
    gca: 'Genome assembly database',
    gen: 'European Nucleotide Archive',
    geo: 'Gene Expression Omnibus (GEO)',
    gisaid: 'GISAID',
    go: 'Gene Ontology',
    hgnc: 'HUGO Gene Nomenclature Committee',
    hipsci: 'Human induced pluripotent stem cell initiative',
    hpa: 'The Human Protein Atlas',
    igsr: 'The International Genome Sample Resource',
    intact: 'IntAct',
    interpro: 'InterPro',
    metabolights: 'MetaboLights',
    metagenomics: 'MGnify',
    mint: 'Molecular INTeraction Database (MINT)',
    nct: 'ClinicalTrials.gov',
    omim: 'Online Mendelian Inheritance in Man(OMIM)',
    orphadata: 'Orphadata',
    pdb: 'The Protein Data Bank',
    pfam: 'Pfam Protein Families',
    pxd: 'PRIDE Proteomics Identification Database',
    reactome: 'Reactome',
    refseq: 'NCBI Reference Sequence Database',
    refsnp: 'dbSNP Reference SNP',
    rfam: 'Rfam',
    rnacentral: 'RNAcentral',
    rrid: 'Research Resource Identifiers',
    treefam: 'TreeFam',
    uniparc: 'UniParc',
    uniprot: 'UniProt'
}

module.exports = {
    LABEL_REPOSITORY_MAPPING,
}